### ISSUE TITLE
Modularity not returning graph without edges

### ISSUE THREAD

**Issue by matzehecht** [graphology/graphology-metrics#15]
I do have a small graph with three nodes and no edges between them.  
If I try to calculate their modularity the modularity function does not return.
Please let me know if you need more information.

**Comment by Yomguithereal** [comment]
Hello @matzehecht, if I remember correctly, the various modularity function throw when given graphs with no edges, which is expected since you cannot compute the modularity of an empty graph. Can you provide a minimal reproducible example so I can check whether we missed something please?

**Comment by matzehecht** [comment]
@Yomguithereal thanks for the response... Sorry... My bad... I've missed that...  
Means: everything is working as it should. The function throws an Error with the message: `graphology-metrics/modularity: cannot compute modularity of an empty graph.` 
I will close this issue as it is solved...
