### ISSUE TITLE
Modularity and community detection on directed graphs

### ISSUE THREAD

**Issue by deemeetree** [graphology/graphology-metrics#7]
I saw that some libraries (like, for example, Louvain community detection based on the same Blondel algorithm implemented in networkx python library that you seem to be using also in Graphology) are not doing community detection and modularity calculation for directed graphs due to the absence of the consensus on how to calculate modularity for directed graphs.

However, graphology can process directed graphs for community detection.

Could you please elaborate how your algorithm works in such cases (directed graphs)? Or do you simply treat is as undirected for community detection purposes?

More on this here:
https://github.com/taynaud/python-louvain/issues/28

**Comment by deemeetree** [comment]
Ok, I saw in the https://github.com/graphology/graphology-metrics/blob/master/modularity.js that you don't consider directed graphs and that weights are chosen arbitrarily, so it is better to add them before passing the graph to the `modularity` function. 

Also, you may be interested, I compared your modularity algorithm results with https://github.com/noduslabs/jLouvain (by @upphiminn) and I found that while the partition results (communities) are more or less consistent, the measures of modularity are always a bit different.

However, the algorithm you implement (both in terms of partition and modularity measure) is almost always consistent with https://github.com/taynaud/python-louvain (I also tagged the discussion above).

Another python library that calculates partition is https://github.com/vtraag/louvain-igraph but its results are a bit different from the `python-louvain` above and its modularity measure is further away from yours. 

I thought I'd leave this information here for future use.

**Comment by Yomguithereal** [comment]
Hello @deemeetree,

Did you also check [graphology-communities-louvain](https://github.com/graphology/graphology-communities-louvain)?

**Comment by deemeetree** [comment]
@Yomguithereal  No, what's the different between the two?

**Comment by Yomguithereal** [comment]
Hello @deemeetree. I revamped modularity completely. It should be correct now and aligned with most implementation for the undirected case. I also went ahead and implemented the true directed modularity (which is almost never correctly computed anywhere).

**Comment by deemeetree** [comment]
Hello @Yomguithereal — that is great, thank you very much for that and I'm going to implement it into InfraNodus soon and give you my feedback. Well done!
